version: '3.2'

services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always

    container_name: iris-hl7qs

    ports:
      - "1972"
      - "52795:52773"
      - "53773"

    hostname: server-hl7qs

    volumes:
      - ./:/iris/app
